version: "3"
services:
    xo-pet-api-app:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
            args:
                USER: pet_api_user
        image: laravel-10/php-8.2
        container_name: xo-pet-api-app
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
            - ./docker/php/dev.ini:/usr/local/etc/php/conf.d/dev.ini
        networks:
            - xo-pet-api-network

    xo-pet-api-server:
        image: nginx:1.23-alpine
        container_name: xo-pet-api-server
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - xo-pet-api-network

    xo-pet-api-db:
        image: mysql:8.0
        container_name: xo-pet-api-db
        restart: unless-stopped
        ports:
            - 33060:3306
        volumes:
            - xo-pet-api-volume-mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
        networks:
            - xo-pet-api-network

networks:
    xo-pet-api-network:
        driver: bridge
        name: xo-pet-api-network

volumes:
    xo-pet-api-volume-mysql:
        driver: local

